Repository Joel-leal/voting-system, pull requests merged in 2022-06, with the labels that each got.

#14 feat: add linting to project
  .editorconfig
  .eslintrc.yml
  .github/workflows/merge-request.yaml
  .prettierignore
  .prettierrc.yml
  next.config.js
  package.json
  pages/_app.tsx
  pages/api/hello.ts
  pages/index.tsx
  yarn.lock
Labels: enhancement

#10 Instalação e configuração do Chakra Ui no projeto
  package.json
  pages/_app.tsx
  pages/index.tsx
  public/favicon.ico
  yarn.lock
Labels: enhancement

#17 Criação do botão base do projeto.
  src/components/BaseButton.tsx
Labels: enhancement

#22 feat: add get avaiable elections endpoint
  .env.local
  .env.local.example
  .gitignore
  .prettierignore
  README.md
  package.json
  packages/entities/notion.ts
  packages/notion/client.ts
  packages/notion/sdk.ts
  packages/notion/utils.ts
  pages/api/elections/index.ts
  pages/api/hello.ts
  yarn.lock
Labels: enhancement

#23 feat: add create page endpoint
  packages/entities/notion.ts
  packages/notion/client.ts
  packages/notion/templates.ts
  pages/api/elections/result.ts
Labels: enhancement

#24 feat: add get page by id endpoint
  packages/entities/notion.ts
  packages/notion/client.ts
  packages/notion/sdk.ts
  packages/notion/utils.ts
  pages/api/elections/index.ts
  pages/api/elections/page.ts
Labels: enhancement

#28 Fea/add pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement, good first issue

#31 refactor: move src/components to packages
  packages/components/BaseButton.tsx
Labels: refactor

#21 feat: add election select for index page
  pages/index.tsx
Labels: enhancement

#33 feat: add configuration menu
  package.json
  packages/components/ConfigModal/ConfigForm.tsx
  packages/components/ConfigModal/index.tsx
  packages/components/NavBar.tsx
  packages/entities/config-modal.ts
  pages/index.tsx
  yarn.lock
Labels: enhancement

#34 feat: add context for config form
  packages/components/ConfigModal/ConfigForm.tsx
  packages/components/ConfigModal/index.tsx
  packages/entities/config-modal.ts
  packages/features/config-context.tsx
  packages/utils/createCtx.ts
  packages/utils/react.tsx
  pages/_app.tsx
Labels: enhancement
